### ISSUE TITLE
vertical-align not working in FF40

### ISSUE THREAD

**Issue by visualcookie** [esr360/Kayzen-GS#5]
Somehow vertical alignment of columns won't work in FF40.

**Comment by visualcookie** [comment]
I removed `display: table !important;` from the `.row` and set it to `display: block !important;` which also seems to work cross browser.

**Comment by esr360** [comment]
If you change the `display: table;` to `display: block;`, you may find that if you use certain fonts the column widths do not totally add up to 100%. This was at least the initial reason for using `display: table;`, but since then, the `letter-spacing` property on the `row` element has increased from some small magic number to  `-1em`, which _may_ now render the `display: table;` property redundant, which would be fantastic if so. I'll definitely do some testing.
